### ISSUE TITLE
Maven SolarSearch: Throwing 504 Errors Intermittently 

### ISSUE THREAD

**Issue by dw-develop** [sonatype-nexus-community/search-maven-org#153]
* **What are you trying to do?**
Executing script that hits this solar search endpoint.  Most of the time it returns 504. 

URL: http://search.maven.org/solrsearch/select?q=1:%2283cd2cd674a217ade95a4bb83a8a14f351f48bd0%22&rows=20&wt=json

504 Gateway Time-out
nginx

```
http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 504 for URL: http://search.maven.org/solrsearch/select?q=1:%2283cd2cd674a217ade95a4bb83a8a14f351f48bd0%22&rows=20&wt=json
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at sailpoint.services.cicd.maven.util.JarDependencyLookup.getSingleJarInfo(JarDependencyLookup.java:72)
        at sailpoint.services.cicd.maven.util.JarDependencyLookup.main(JarDependencyLookup.java:28)
```

**Comment by SirMaster** [comment]
@Dweston88 thank you for reaching out. This project is specifically related to the Front End of Search Maven Org and it appears that what you are attempting to do is related to the Back end Services of maven central. I confirmed with our other engineers.

Feel free to open a ticket on  https://issues.sonatype.org/projects/MVNCENTRAL with your concerns.

Have a great day!
